FROM golang:1.24-alpine AS builder

# Set environment
WORKDIR /app

# Install git and build tools
RUN apk add --no-cache git

# Copy go.mod and go.sum
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy source code
COPY . .

# Run the migration script
CMD ["sh", "-c", "go run cmd/migration/*.go -type=run"]